config/routes.rb
Rails.application.routes.draw do
    root 'sessions#new'  
    post '/login', to: 'sessions#create'  
    get '/success', to: 'success#show'  

    resources :books
    resources :lectors
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :lector

  validates :title, presence: true
  validates :author, presence: true
  validates :is_borrowed, inclusion: { in: [true, false] }

 
  validate :date_presence_based_on_is_borrowed

  before_create :generate_uuid

  before_save :reset_date_and_lector_if_not_borrowed

  private

  def generate_uuid
    self.id ||= SecureRandom.uuid
  end


  def date_presence_based_on_is_borrowed
    if is_borrowed && date.nil?
      errors.add(:date, "doit être spécifiée si le livre est emprunté.")
    end

    if !is_borrowed && !date.nil?
      errors.add(:date, "doit être vide si le livre n'est pas emprunté.")
    end

    if is_borrowed && lector.nil?
      errors.add(:lector, "doit être associé si le livre est emprunté.")
    end
  end

  # Réinitialiser la date et supprimer l'association avec lector si 'is_borrowed' devient false
  def reset_date_and_lector_if_not_borrowed
    if !is_borrowed
      self.date = nil
      self.lector = nil
    end
  end
end

app/models/lector.rb
class Lector < ApplicationRecord
    has_many :books
    # Callback pour générer le UUID avant la création
    before_create :generate_uuid
  
    # Validation des autres attributs
    validates :first_name, :last_name, :address, :email, presence: true
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

    def full_name
        "#{first_name} #{last_name}"
      end

  
    private
  
    # Méthode pour générer le UUID
    def generate_uuid
      self.uuid ||= SecureRandom.uuid
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: 'Le livre a été ajouté avec succès.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    if @book.update(book_params)
      redirect_to books_path, notice: 'Le livre a été mis à jour avec succès.'
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @book.destroy
    redirect_to books_path, notice: 'Le livre a été supprimé avec succès.'
  end
  

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :is_borrowed, :date, :lector_id)
  end
end

app/controllers/lectors_controller.rb
class LectorsController < ApplicationController
    before_action :set_lector, only: %i[show edit update destroy]
  
    # GET /lectors
    def index
      @lectors = Lector.all
    end
  
    def show
        @books = @lector.books || [] # Si @lector.books est nil, on assigne une liste vide
      end
    # GET /lectors/new
    def new
      @lector = Lector.new
    end
  
    # POST /lectors
    def create
      @lector = Lector.new(lector_params)
  
      if @lector.save
        redirect_to @lector, notice: 'Le lecteur a ete ajoute.'
      else
        render :new
      end
    end
  
    # GET /lectors/1/edit
    def edit
    end
  
    # PATCH/PUT /lectors/1
    def update
      if @lector.update(lector_params)
        redirect_to @lector, notice: 'Mis a jouer.'
      else
        render :edit
      end
    end
  
    # DELETE /lectors/1
    def destroy
      @lector.destroy
      redirect_to lectors_url, notice: 'Le lecteur a quitté notre base de donnée'
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_lector
      @lector = Lector.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def lector_params
      params.require(:lector).permit(:first_name, :last_name, :address, :email, :uuid)
    end
  end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  
  end

  def create
    username = params[:username]
    password = params[:password]

    if username == "Admin" && password == "Paris2023!"
      redirect_to success_path  
    else
      flash.now[:alert] = "Invalid username or password"
      render :new
    end
  end
end

app/controllers/success_controller.rb
class SuccessController < ApplicationController
    def show
     
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/lectors_helper.rb
module LectorsHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/success_helper.rb
module SuccessHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<!-- app/views/books/edit.html.erb -->
<h1>Modifier le livre : <%= @book.title %></h1>

<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :is_borrowed %>
    <%= form.check_box :is_borrowed, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :lector_id, "Lecteur" %>
    <%= form.collection_select :lector_id, Lector.all, :id, :full_name, { include_blank: true }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit 'Mettre à jour', class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Retour', books_path, class: "btn btn-secondary" %>

app/views/books/index.html.erb
<%= link_to 'Ajouter un livre', new_book_path, class: "button" %>

<table>
  <thead>
    <tr>

      <th>Titre</th>
      <th>Auteur</th>
      <th>Emprunté ?</th>
      <th>Date de retour (si emprunté) </th>
      <th>Lecteur</th> <!-- Colonne pour afficher le lecteur -->
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
     
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.is_borrowed ? "Oui" : "Non" %></td>
        <td><%= book.date || "Non spécifiée" %></td>
        <td>
          <% if book.is_borrowed && book.lector %>
            <%= link_to "#{book.lector.first_name} #{book.lector.last_name}", lector_path(book.lector) %> <!-- Lien vers la page show du lector -->
          <% else %>
            Non emprunté
          <% end %>
        </td>
        <td>
          <%= link_to 'Modifier', edit_book_path(book) %> |
          <%= link_to 'Supprimer', book_path(book), method: :delete, data: { confirm: 'Confirmer suppression?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= button_to "Gestion de livres", books_path, method: :get, class: "btn btn-primary custom-button" %>
<%= button_to "Relation avec les lecteurs", lectors_path, method: :get, class: "btn btn-secondary custom-button" %>

app/views/books/new.html.erb
<h1>Ajouter un nouveau livre</h1>

<%= form_with model: @book, local: true do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "erreur") %> empêchent la création du livre :</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, "Titre" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
  <%= form.label :author, "Auteurs (séparés par des virgules)" %>
  <%= form.text_field :author, value: @book.author.present? ? @book.author.join(", ") : "" %>
</div>

  <div class="field">
    <%= form.label :is_borrowed, "Emprunté ?" %>
    <%= form.check_box :is_borrowed %>
  </div>

  <div class="field">
    <%= form.label :date, "Date de retour (optionnel)" %>
    <%= form.date_field :date %>
  </div>

  <div class="actions">
    <%= form.submit "Créer le livre", class: 'btn btn-success' %>
  </div>
<% end %>

<%= link_to 'Retour à la liste', books_path, class: 'btn btn-secondary' %>

app/views/books/show.html.erb
<!-- app/views/books/show.html.erb -->
<h1><%= @book.title %></h1>
<p><strong>Auteur :</strong> <%= @book.author %></p>
<p><strong>Emprunté :</strong> <%= @book.is_borrowed ? 'Oui' : 'Non' %></p>
<p><strong>Date de retour :</strong> <%= @book.date %></p>
<%= link_to 'Modifier', edit_book_path(@book) %> |
<%= link_to 'Supprimer', @book, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer ce livre ?' } %> |
<%= link_to 'Retourner à la liste de livres', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Fun Library" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
  <body>

  <header>
    <h1>Application demo Ruby on rails</h1>
  </header>

  <!-- Messages Flash -->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <!-- Contenu de la page -->
  <%= yield %>

  <footer>
    <p>&copy;  </p>
  </footer>
</body>

</html>

app/views/lectors/edit.html.erb
<h1>Edit Lector</h1>

<%= form_with(model: @lector, local: true) do |form| %>
  <% if @lector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lector.errors.count, "error") %> prohibited this lector from being saved:</h2>
      <ul>
        <% @lector.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :uuid %>
    <%= form.text_field :uuid, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit 'Update Lector', class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Back', lectors_path, class: 'btn btn-secondary' %>

app/views/lectors/index.html.erb
<h1>Lectors</h1>

<%= link_to 'Ajouter un nouveau lecteur', new_lector_path %>

<table>
  <thead>
    <tr>
      <th>Prénom</th>
      <th>Nom</th>
      <th>Addresse</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @lectors.each do |lector| %>
      <tr>
        <td><%= lector.first_name %></td>
        <td><%= lector.last_name %></td>
        <td><%= lector.address %></td>
        <td><%= lector.email %></td>

        <td>
          <%= link_to 'Afficher', lector_path(lector) %> |
          <%= link_to 'Editer', edit_lector_path(lector) %> |
          <%= link_to 'Supprimer', lector_path(lector), method: :delete, data: { confirm: 'Etes vous sur ?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= button_to "Gestion de livres", books_path, method: :get, class: "btn btn-primary custom-button" %>
<%= button_to "Relation avec les lecteurs", lectors_path, method: :get, class: "btn btn-secondary custom-button" %>

app/views/lectors/new.html.erb
<h1>New Lector</h1>

<%= form_with(model: @lector, local: true) do |form| %>
  <% if @lector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lector.errors.count, "error") %> prohibited this lector from being saved:</h2>
      <ul>
        <% @lector.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= form.submit "Create Lector", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lectors/show.html.erb
<!-- app/views/lectors/show.html.erb -->

<h1><%= @lector.first_name %> <%= @lector.last_name %></h1>
<p><%= @lector.address %></p>
<p><%= @lector.email %></p>

<h2>Livres associés :</h2>
<% if @books && @books.any? %> 
  <ul>
    <% @books.each do |book| %>
      <li>
        <%= link_to book.title, book_path(book) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Aucun livre associé.</p>
<% end %>

<%= link_to 'Retour', lectors_path, class: 'btn btn-secondary' %>

app/views/success/show.html.erb
<!-- app/views/success/show.html.erb -->

<h1>Bravo :)</h1>
<p>Vous êtes connecté !</p>
<%= button_to "Gestion de livres", books_path, method: :get, class: "btn btn-primary custom-button" %>
<%= button_to "Relation avec les lecteurs", lectors_path, method: :get, class: "btn btn-secondary custom-button" %>

<div class="sucess-image">